project_id = "sxzmtnsfsyifujdnqyzr"

[functions.register]
verify_jwt = false

[functions.delete-user]
verify_jwt = false

[functions.login]
verify_jwt = false

[functions.evolution]
verify_jwt = false

[functions.evolution-notify]
verify_jwt = false

[functions.appointment-reminder]
verify_jwt = false

[functions.admin-update-appointment]
verify_jwt = false

[functions.admin-update-credentials]
verify_jwt = false

[functions.google-reviews]
verify_jwt = false

[functions.admin-create-partner-account]
verify_jwt = false